// Package genprops generates type-safe property definitions for GORM models.
//
// It parses GORM model fields via schema.Parse and generates a corresponding
// typed property dictionary. These properties can be used to build query
// conditions with a type-safe SQL-building experience.
//
// It supports a custom naming strategy and allows configuring the output package
// name and file name. By default, it auto-detects them from the model package and name.
package genprops

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/fsx"
	"github.com/im-wmkong/gorm-query/internal/reflectx"
	"gorm.io/gorm/schema"
)

const queryPkg = "github.com/im-wmkong/gorm-query/query"

type Generator struct {
	cfg config
}

// New creates a new Generator.
//
// Example:
//
//	g := genprops.New(
//	    genprops.WithOutputDir("./model"),
//	    genprops.WithOutputFile("props_gen.go"),
//	)
//	_ = g
func New(opts ...Option) *Generator {
	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Generator{cfg: cfg}
}

// Generate parses the given GORM models and generates a props file into outputDir.
//
// Example:
//
//	// Generate props into the same package as the models.
//	err := genprops.New(genprops.WithOutputDir("./model")).Generate(&model.User{})
//	_ = err
func (g *Generator) Generate(models ...any) error {
	// Filter out nil models.
	filtered := make([]any, 0, len(models))
	for _, model := range models {
		if model != nil {
			filtered = append(filtered, model)
		}
	}
	nilCount := len(models) - len(filtered)
	models = filtered

	if nilCount > 0 {
		g.cfg.logger.Debug("filtered %d nil model(s), %d remaining", nilCount, len(models))
	}

	if len(models) == 0 {
		return fmt.Errorf("no models provided")
	}

	// Determine package name.
	pkgName := g.cfg.packageName
	if pkgName == "" {
		pkgName = reflectx.PackageName(models[0])
		g.cfg.logger.Debug("auto-detected package name: %s", pkgName)

		// When auto-detecting, ensure all models are in the same package.
		for _, model := range models {
			if reflectx.PackageName(model) != pkgName {
				return fmt.Errorf("all models must be in the same package or explicitly set WithPackageName")
			}
		}
	} else {
		g.cfg.logger.Debug("using explicit package name: %s", pkgName)
	}

	// Ensure the output directory exists.
	if err := os.MkdirAll(g.cfg.outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir failed: %w", err)
	}

	// Detect existing package name in outputDir.
	detectedPkg, err := fsx.PackageNameFromDir(g.cfg.outputDir)
	if err != nil {
		return fmt.Errorf("detect package failed: %w", err)
	}
	if detectedPkg != "" && detectedPkg != pkgName {
		return fmt.Errorf(
			"package mismatch: outputDir has package %q, but generator uses %q",
			detectedPkg,
			pkgName,
		)
	}

	// Generate code.
	g.cfg.logger.Info("generating props for %d model(s)", len(models))

	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by genprops. DO NOT EDIT.")

	seen := make(map[string]struct{})
	schemaCache := &sync.Map{}

	for _, model := range models {
		sch, err := schema.Parse(model, schemaCache, g.cfg.namingStrategy)
		if err != nil {
			return fmt.Errorf("gorm schema parse failed: %w", err)
		}

		if len(sch.Fields) == 0 {
			g.cfg.logger.Warn("skipping model %s: no schema fields", sch.Name)
			continue
		}

		// Deduplicate by model name.
		if _, ok := seen[sch.Name]; ok {
			g.cfg.logger.Warn("skipping duplicate model: %s", sch.Name)
			continue
		}
		seen[sch.Name] = struct{}{}

		g.cfg.logger.Debug("parsed model %s: %d field(s)", sch.Name, len(sch.Fields))

		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", sch.Name, sch.Name))

		f.Var().Id(sch.Name+"Props").Op("=").StructFunc(func(grp *jen.Group) {
			for _, field := range sch.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Qual(queryPkg, "Column")
			}
		}).CustomFunc(jen.Options{
			Open:      "{",
			Close:     "}",
			Separator: ",",
			Multi:     true,
		}, func(grp *jen.Group) {
			for _, field := range sch.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Op(":").Lit(field.DBName)
			}
		})

		f.Line()
	}

	// Render code.
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return fmt.Errorf("render failed: %w", err)
	}

	filename := filepath.Join(g.cfg.outputDir, g.cfg.outputFile)

	// dry-run
	if g.cfg.dryRun {
		old, _ := os.ReadFile(filename)
		if !bytes.Equal(old, buf.Bytes()) {
			return fmt.Errorf("generated file outdated: %s", filename)
		}
		g.cfg.logger.Info("dry-run passed: %s is up to date", filename)
		return nil
	}

	// Avoid rewriting unchanged content.
	if old, err := os.ReadFile(filename); err == nil {
		if bytes.Equal(old, buf.Bytes()) {
			g.cfg.logger.Debug("skipped writing %s: content unchanged", filename)
			return nil
		}
	}

	// Write file.
	if err := os.WriteFile(filename, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write file failed: %w", err)
	}

	g.cfg.logger.Info("generated %s", filename)

	return nil
}
