// Package genprops 是一个为 GORM 模型生成强类型属性代码的工具。
//
// 它通过 schema.Parse 函数解析 GORM 模型的字段，生成对应的强类型属性字典。
// 这些属性字典可以用于构建查询条件，提供类型安全的 SQL 构建体验。
//
// 它支持自定义命名策略，允许用户根据需要调整生成的代码的包名、文件名等。
// 默认情况下，它会根据模型的包名和模型名自动生成属性字典的包名和文件名。
package genprops

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/fsx"
	"github.com/im-wmkong/gorm-query/internal/reflectx"
	"gorm.io/gorm/schema"
)

const queryPkg = "github.com/im-wmkong/gorm-query/query"

type Generator struct {
	cfg config
}

func New(opts ...Option) *Generator {
	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Generator{cfg: cfg}
}

func (g *Generator) Generate(models ...any) error {
	// 过滤 nil 元素
	filtered := make([]any, 0, len(models))
	for _, model := range models {
		if model != nil {
			filtered = append(filtered, model)
		}
	}
	nilCount := len(models) - len(filtered)
	models = filtered

	if nilCount > 0 {
		g.cfg.logger.Debug("filtered %d nil model(s), %d remaining", nilCount, len(models))
	}

	if len(models) == 0 {
		return fmt.Errorf("no models provided")
	}

	// 确定 packageName
	pkgName := g.cfg.packageName
	if pkgName == "" {
		pkgName = reflectx.PackageName(models[0])
		g.cfg.logger.Debug("auto-detected package name: %s", pkgName)

		// 自动推导时校验同包
		for _, model := range models {
			if reflectx.PackageName(model) != pkgName {
				return fmt.Errorf("all models must be in the same package or explicitly set WithPackageName")
			}
		}
	} else {
		g.cfg.logger.Debug("using explicit package name: %s", pkgName)
	}

	// 确保目录存在
	if err := os.MkdirAll(g.cfg.outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir failed: %w", err)
	}

	// 检测目录已有 package
	detectedPkg, err := fsx.PackageNameFromDir(g.cfg.outputDir)
	if err != nil {
		return fmt.Errorf("detect package failed: %w", err)
	}
	if detectedPkg != "" && detectedPkg != pkgName {
		return fmt.Errorf(
			"package mismatch: outputDir has package %q, but generator uses %q",
			detectedPkg,
			pkgName,
		)
	}

	// 生成代码
	g.cfg.logger.Info("generating props for %d model(s)", len(models))

	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by genprops. DO NOT EDIT.")

	seen := make(map[string]struct{})
	schemaCache := &sync.Map{}

	for _, model := range models {
		sch, err := schema.Parse(model, schemaCache, g.cfg.namingStrategy)
		if err != nil {
			return fmt.Errorf("gorm schema parse failed: %w", err)
		}

		if len(sch.Fields) == 0 {
			g.cfg.logger.Warn("skipping model %s: no schema fields", sch.Name)
			continue
		}

		// 去重
		if _, ok := seen[sch.Name]; ok {
			g.cfg.logger.Warn("skipping duplicate model: %s", sch.Name)
			continue
		}
		seen[sch.Name] = struct{}{}

		g.cfg.logger.Debug("parsed model %s: %d field(s)", sch.Name, len(sch.Fields))

		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", sch.Name, sch.Name))

		f.Var().Id(sch.Name+"Props").Op("=").StructFunc(func(grp *jen.Group) {
			for _, field := range sch.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Qual(queryPkg, "Column")
			}
		}).CustomFunc(jen.Options{
			Open:      "{",
			Close:     "}",
			Separator: ",",
			Multi:     true,
		}, func(grp *jen.Group) {
			for _, field := range sch.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Op(":").Lit(field.DBName)
			}
		})

		f.Line()
	}

	// 渲染代码
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return fmt.Errorf("render failed: %w", err)
	}

	filename := filepath.Join(g.cfg.outputDir, g.cfg.outputFile)

	// dry-run
	if g.cfg.dryRun {
		old, _ := os.ReadFile(filename)
		if !bytes.Equal(old, buf.Bytes()) {
			return fmt.Errorf("generated file outdated: %s", filename)
		}
		g.cfg.logger.Info("dry-run passed: %s is up to date", filename)
		return nil
	}

	// 避免重复写
	if old, err := os.ReadFile(filename); err == nil {
		if bytes.Equal(old, buf.Bytes()) {
			g.cfg.logger.Debug("skipped writing %s: content unchanged", filename)
			return nil
		}
	}

	// 写文件
	if err := os.WriteFile(filename, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write file failed: %w", err)
	}

	g.cfg.logger.Info("generated %s", filename)

	return nil
}
