// Package genprops 是一个为 GORM 模型生成强类型属性代码的工具。
//
// 它通过 schema.Parse 函数解析 GORM 模型的字段，生成对应的强类型属性字典。
// 这些属性字典可以用于构建查询条件，提供类型安全的 SQL 构建体验。
//
// 它支持自定义命名策略，允许用户根据需要调整生成的代码的包名、文件名等。
// 默认情况下，它会根据模型的包名和模型名自动生成属性字典的包名和文件名。
package genprops

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/fsx"
	"github.com/im-wmkong/gorm-query/internal/reflectx"
	"gorm.io/gorm/schema"
)

const queryPkg = "github.com/im-wmkong/gorm-query/query"

type Generator struct {
	cfg config
}

func New(opts ...Option) *Generator {
	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Generator{cfg: cfg}
}

func (g *Generator) GenerateAll(models []any) error {
	if len(models) == 0 {
		return fmt.Errorf("no models provided")
	}

	// 确定 packageName
	pkgName := g.cfg.packageName
	if pkgName == "" {
		pkgName = reflectx.PackageName(models[0])

		// 自动推导时校验同包
		for _, m := range models {
			if reflectx.PackageName(m) != pkgName {
				return fmt.Errorf("all models must be in the same package or explicitly set WithPackageName")
			}
		}
	}

	// 确保目录存在
	if err := os.MkdirAll(g.cfg.outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir failed: %w", err)
	}

	// 检测目录已有 package
	detectedPkg, err := fsx.PackageNameFromDir(g.cfg.outputDir)
	if err != nil {
		return fmt.Errorf("detect package failed: %w", err)
	}

	if detectedPkg != "" && detectedPkg != pkgName {
		return fmt.Errorf(
			"package mismatch: outputDir has package %q, but generator uses %q",
			detectedPkg,
			pkgName,
		)
	}

	// 生成代码
	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by genprops. DO NOT EDIT.")

	seen := make(map[string]struct{})

	for _, m := range models {
		s, err := schema.Parse(m, &sync.Map{}, g.cfg.namingStrategy)
		if err != nil {
			return fmt.Errorf("gorm schema parse failed: %w", err)
		}

		if len(s.Fields) == 0 {
			continue
		}

		// 去重
		if _, ok := seen[s.Name]; ok {
			continue
		}
		seen[s.Name] = struct{}{}

		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", s.Name, s.Name))

		f.Var().Id(s.Name+"Props").Op("=").StructFunc(func(grp *jen.Group) {
			for _, field := range s.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Qual(queryPkg, "Column")
			}
		}).CustomFunc(jen.Options{
			Open:      "{",
			Close:     "}",
			Separator: ",",
			Multi:     true,
		}, func(grp *jen.Group) {
			for _, field := range s.Fields {
				if field.DBName == "" {
					continue
				}
				grp.Id(field.Name).Op(":").Lit(field.DBName)
			}
		})

		f.Line()
	}

	// 渲染代码
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return fmt.Errorf("render failed: %w", err)
	}

	filename := filepath.Join(g.cfg.outputDir, g.cfg.outputFile)

	// dry-run
	if g.cfg.dryRun {
		old, _ := os.ReadFile(filename)
		if !bytes.Equal(old, buf.Bytes()) {
			return fmt.Errorf("generated file outdated: %s", filename)
		}
		return nil
	}

	// 避免重复写
	if old, err := os.ReadFile(filename); err == nil {
		if bytes.Equal(old, buf.Bytes()) {
			return nil
		}
	}

	// 写文件
	if err := os.WriteFile(filename, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write file failed: %w", err)
	}

	if g.cfg.logger != nil {
		g.cfg.logger("generated %s", filename)
	}

	return nil
}

func (g *Generator) Generate(model any) error {
	return g.GenerateAll([]any{model})
}
