package genprops

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type user struct {
	gorm.Model
	UserName string `gorm:"column:user_name;size:255;not null"`
	Email    string `gorm:"column:email;size:255;unique"`
	Age      int    `gorm:"column:age"`
	Status   int    `gorm:"column:status;default:1"` // 1: active, 0: inactive
}

type localGenPropsModel struct {
	ID uint
}

type emptyGenPropsModel struct{}

type partiallyIgnoredGenPropsModel struct {
	ID      uint
	Name    string `gorm:"column:name"`
	Ignored string `gorm:"-"`
}

type testLogger struct {
	infoCalls  int
	debugCalls int
	warnCalls  int
}

func (l *testLogger) Debug(string, ...any) { l.debugCalls++ }
func (l *testLogger) Info(string, ...any)  { l.infoCalls++ }
func (l *testLogger) Warn(string, ...any)  { l.warnCalls++ }

func TestFilterNilModels(t *testing.T) {
	filtered, nilCount := New().filterNilModels([]any{nil, &user{}, nil, &localGenPropsModel{}})
	require.Len(t, filtered, 2)
	assert.Equal(t, 2, nilCount)
	assert.IsType(t, &user{}, filtered[0])
	assert.IsType(t, &localGenPropsModel{}, filtered[1])
}

func TestGeneratorResolvePackageName(t *testing.T) {
	g := New()

	pkgName, err := g.packageName([]any{&user{}, &localGenPropsModel{}})
	require.NoError(t, err)
	assert.Equal(t, "genprops", pkgName)
}

func TestGenPropsGenerate_SuccessAndIdempotent(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "ignored_test.go"), []byte("package ignored\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "notes.txt"), []byte("plain text"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "invalid.go"), []byte("var broken = 1\n"), 0644))
	require.NoError(t, os.Mkdir(filepath.Join(outDir, "nested"), 0755))
	require.NoError(t, os.Symlink(filepath.Join(outDir, "missing.go"), filepath.Join(outDir, "broken_link.go")))

	tl := &testLogger{}
	g := New(
		WithOutputDir(outDir),
		WithOutputFile("custom_props.go"),
		WithPackageName("model"),
		WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
		WithLogger(tl),
	)

	err := g.Generate(&user{}, &user{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "custom_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "Code generated by genprops. DO NOT EDIT.")
	assert.Contains(t, generated, "package model")
	assert.Contains(t, generated, "var userProps = struct")
	assert.Contains(t, generated, "UserName")
	assert.Contains(t, generated, "query.Column")
	assert.Contains(t, generated, "DeletedAt query.Column")
	assert.Contains(t, generated, `UserName:  "user_name"`)
	assert.Contains(t, generated, `import query "github.com/im-wmkong/gorm-query/query"`)
	assert.Equal(t, 1, strings.Count(generated, "var userProps = struct"))

	// First run: Info contains "generating props..." and "generated ...".
	assert.Equal(t, 2, tl.infoCalls)
	// Duplicate user triggers one Warn.
	assert.Equal(t, 1, tl.warnCalls)
	assert.Greater(t, tl.debugCalls, 0)

	prevInfo := tl.infoCalls
	err = g.Generate(&user{})
	require.NoError(t, err)
	// Idempotent: unchanged content skips writing; only Debug is emitted.
	// Info should not increase except "generating props...".
	assert.Equal(t, prevInfo+1, tl.infoCalls)
}

func TestGenPropsGenerate_WithExplicitPackageNameForMixedModels(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithOutputFile("mixed_props.go"),
		WithPackageName("model"),
	).Generate(&user{}, &localGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "mixed_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "userProps defines the fields for user")
	assert.Contains(t, generated, "localGenPropsModelProps defines the fields for localGenPropsModel")
	assert.Contains(t, generated, "var localGenPropsModelProps = struct")
	assert.Contains(t, generated, `ID: "id"`)
}

func TestGenPropsGenerate_SkipsModelsWithoutSchemaFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithOutputFile("empty_props.go"),
		WithPackageName("test"),
	).Generate(&emptyGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "empty_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "package test")
	assert.NotContains(t, generated, "Props defines the fields")
}

func TestGenPropsGenerate_SkipsIgnoredFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithOutputFile("ignored_props.go"),
		WithPackageName("test"),
	).Generate(&partiallyIgnoredGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "ignored_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "partiallyIgnoredGenPropsModelProps defines the fields for partiallyIgnoredGenPropsModel")
	assert.Contains(t, generated, "ID:")
	assert.Contains(t, generated, "Name query.Column")
	assert.NotContains(t, generated, "Ignored query.Column")
	assert.NotContains(t, generated, `Ignored: "`)
}

func TestGenPropsGenerate_DryRun(t *testing.T) {
	outDir := t.TempDir()

	g := New(WithOutputDir(outDir))
	require.NoError(t, g.Generate(&user{}))

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithDryRun(true),
	)
	require.NoError(t, dryRunGenerator.Generate(&user{}))

	propsFile := filepath.Join(outDir, "props_gen.go")
	// Keep the package in outputDir consistent with the auto-detected package name;
	// otherwise dry-run will fail earlier due to package mismatch.
	require.NoError(t, os.WriteFile(propsFile, []byte("package genprops\n"), 0644))

	err := dryRunGenerator.Generate(&user{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file outdated")
	assert.Contains(t, err.Error(), propsFile)
}

func TestGenPropsGenerate_ErrorScenarios(t *testing.T) {
	t.Run("no models", func(t *testing.T) {
		err := New().Generate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no models provided")
	})

	t.Run("WithLogger nil does not panic", func(t *testing.T) {
		g := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("model"),
			WithLogger(nil),
		)
		err := g.Generate(&user{})
		require.NoError(t, err)
	})

	t.Run("mixed packages without explicit package name", func(t *testing.T) {
		// Use an anonymous struct as the second arg (reflect.Type.PkgPath() == "") to simulate
		// a different package and trigger the "all models must be in the same package" validation
		// without depending on example/model.
		err := New(WithOutputDir(t.TempDir())).Generate(&user{}, &struct{ ID uint }{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "all models must be in the same package")
	})

	t.Run("package mismatch in output dir", func(t *testing.T) {
		outDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(outDir, "existing.go"), []byte("// generated elsewhere\n\npackage otherpkg\n"), 0644))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "package mismatch")
	})

	t.Run("create output dir failed", func(t *testing.T) {
		baseDir := t.TempDir()
		blockedPath := filepath.Join(baseDir, "blocked")
		require.NoError(t, os.WriteFile(blockedPath, []byte("not a directory"), 0644))

		err := New(WithOutputDir(blockedPath)).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "create output dir failed")
	})

	t.Run("write file failed", func(t *testing.T) {
		outDir := t.TempDir()

		err := New(
			WithOutputDir(outDir),
			WithOutputFile(filepath.Join("nested", "props_gen.go")),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "write file failed")
	})

	t.Run("detect package failed", func(t *testing.T) {
		outDir := filepath.Join(t.TempDir(), "locked")
		require.NoError(t, os.Mkdir(outDir, 0000))
		t.Cleanup(func() {
			require.NoError(t, os.Chmod(outDir, 0755))
		})

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "detect package failed")
	})

	t.Run("schema parse failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("broken"),
		).Generate(123)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "gorm schema parse failed")
	})

	t.Run("render failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("invalid-package"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "render failed")
	})
}

func TestNopLogger_DoesNotPanic(t *testing.T) {
	l := NopLogger()
	require.NotNil(t, l)

	// no output asserted, just ensure these methods are executed
	l.Debug("debug %s", "x")
	l.Info("info %d", 1)
	l.Warn("warn %v", nil)
}
