package test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/im-wmkong/gorm-query/example/model"
	"github.com/im-wmkong/gorm-query/genprops"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm/schema"
)

type localGenPropsModel struct {
	ID uint
}

type emptyGenPropsModel struct{}

type partiallyIgnoredGenPropsModel struct {
	ID      uint
	Name    string `gorm:"column:name"`
	Ignored string `gorm:"-"`
}

func TestGenPropsGenerate_SuccessAndIdempotent(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "ignored_test.go"), []byte("package ignored\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "notes.txt"), []byte("plain text"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "invalid.go"), []byte("var broken = 1\n"), 0644))
	require.NoError(t, os.Mkdir(filepath.Join(outDir, "nested"), 0755))
	require.NoError(t, os.Symlink(filepath.Join(outDir, "missing.go"), filepath.Join(outDir, "broken_link.go")))

	logCalls := 0
	g := genprops.New(
		genprops.WithOutputDir(outDir),
		genprops.WithOutputFile("custom_props.go"),
		genprops.WithPackageName("model"),
		genprops.WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
		genprops.WithLogger(func(format string, args ...interface{}) {
			logCalls++
		}),
	)

	err := g.Generate(&model.User{}, &model.User{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "custom_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "Code generated by genprops. DO NOT EDIT.")
	assert.Contains(t, generated, "package model")
	assert.Contains(t, generated, "var UserProps = struct")
	assert.Contains(t, generated, "UserName  query.Column")
	assert.Contains(t, generated, "DeletedAt query.Column")
	assert.Contains(t, generated, `UserName:  "user_name"`)
	assert.Contains(t, generated, `import query "github.com/im-wmkong/gorm-query/query"`)
	assert.Equal(t, 1, strings.Count(generated, "var UserProps = struct"))
	assert.Equal(t, 1, logCalls)

	err = g.Generate(&model.User{})
	require.NoError(t, err)
	assert.Equal(t, 1, logCalls)
}

func TestGenPropsGenerate_WithExplicitPackageNameForMixedModels(t *testing.T) {
	outDir := t.TempDir()

	err := genprops.New(
		genprops.WithOutputDir(outDir),
		genprops.WithOutputFile("mixed_props.go"),
		genprops.WithPackageName("model"),
	).Generate(&model.User{}, &localGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "mixed_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "UserProps defines the fields for User")
	assert.Contains(t, generated, "localGenPropsModelProps defines the fields for localGenPropsModel")
	assert.Contains(t, generated, "var localGenPropsModelProps = struct")
	assert.Contains(t, generated, `ID: "id"`)
}

func TestGenPropsGenerate_SkipsModelsWithoutSchemaFields(t *testing.T) {
	outDir := t.TempDir()

	err := genprops.New(
		genprops.WithOutputDir(outDir),
		genprops.WithOutputFile("empty_props.go"),
		genprops.WithPackageName("test"),
	).Generate(&emptyGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "empty_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "package test")
	assert.NotContains(t, generated, "Props defines the fields")
}

func TestGenPropsGenerate_SkipsIgnoredFields(t *testing.T) {
	outDir := t.TempDir()

	err := genprops.New(
		genprops.WithOutputDir(outDir),
		genprops.WithOutputFile("ignored_props.go"),
		genprops.WithPackageName("test"),
	).Generate(&partiallyIgnoredGenPropsModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "ignored_props.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "partiallyIgnoredGenPropsModelProps defines the fields for partiallyIgnoredGenPropsModel")
	assert.Contains(t, generated, "ID:")
	assert.Contains(t, generated, "Name query.Column")
	assert.NotContains(t, generated, "Ignored query.Column")
	assert.NotContains(t, generated, `Ignored: "`)
}

func TestGenPropsGenerate_DryRun(t *testing.T) {
	outDir := t.TempDir()

	g := genprops.New(genprops.WithOutputDir(outDir))
	require.NoError(t, g.Generate(&model.User{}))

	dryRunGenerator := genprops.New(
		genprops.WithOutputDir(outDir),
		genprops.WithDryRun(true),
	)
	require.NoError(t, dryRunGenerator.Generate(&model.User{}))

	propsFile := filepath.Join(outDir, "props_gen.go")
	require.NoError(t, os.WriteFile(propsFile, []byte("package model\n"), 0644))

	err := dryRunGenerator.Generate(&model.User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file outdated")
	assert.Contains(t, err.Error(), propsFile)
}

func TestGenPropsGenerate_ErrorScenarios(t *testing.T) {
	t.Run("no models", func(t *testing.T) {
		err := genprops.New().Generate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no models provided")
	})

	t.Run("mixed packages without explicit package name", func(t *testing.T) {
		err := genprops.New(genprops.WithOutputDir(t.TempDir())).Generate(&model.User{}, &localGenPropsModel{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "all models must be in the same package")
	})

	t.Run("package mismatch in output dir", func(t *testing.T) {
		outDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(outDir, "existing.go"), []byte("// generated elsewhere\n\npackage otherpkg\n"), 0644))

		err := genprops.New(
			genprops.WithOutputDir(outDir),
			genprops.WithPackageName("model"),
		).Generate(&model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "package mismatch")
	})

	t.Run("create output dir failed", func(t *testing.T) {
		baseDir := t.TempDir()
		blockedPath := filepath.Join(baseDir, "blocked")
		require.NoError(t, os.WriteFile(blockedPath, []byte("not a directory"), 0644))

		err := genprops.New(genprops.WithOutputDir(blockedPath)).Generate(&model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "create output dir failed")
	})

	t.Run("write file failed", func(t *testing.T) {
		outDir := t.TempDir()

		err := genprops.New(
			genprops.WithOutputDir(outDir),
			genprops.WithOutputFile(filepath.Join("nested", "props_gen.go")),
		).Generate(&model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "write file failed")
	})

	t.Run("detect package failed", func(t *testing.T) {
		outDir := filepath.Join(t.TempDir(), "locked")
		require.NoError(t, os.Mkdir(outDir, 0000))
		defer os.Chmod(outDir, 0755)

		err := genprops.New(
			genprops.WithOutputDir(outDir),
			genprops.WithPackageName("model"),
		).Generate(&model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "detect package failed")
	})

	t.Run("schema parse failed", func(t *testing.T) {
		err := genprops.New(
			genprops.WithOutputDir(t.TempDir()),
			genprops.WithPackageName("broken"),
		).Generate(123)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "gorm schema parse failed")
	})

	t.Run("render failed", func(t *testing.T) {
		err := genprops.New(
			genprops.WithOutputDir(t.TempDir()),
			genprops.WithPackageName("invalid-package"),
		).Generate(&model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "render failed")
	})
}
