package main

import (
	"fmt"
	"go/types"
	"log"
	"reflect"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
	"gorm.io/gorm/schema"
)

type FieldInfo struct {
	FieldName  string
	ColumnName string
}

type Generator struct {
	pkgName    string
	data       map[string][]FieldInfo // TypeName -> Fields
	outputPath string
}

func (g *Generator) processTypes(pkg *packages.Package) {
	typesList := strings.Split(*typeNames, ",")
	for _, typeName := range typesList {
		obj := pkg.Types.Scope().Lookup(typeName)
		if obj == nil {
			log.Printf("警告: 在包 %s 中未找到类型 %s", pkg.Name, typeName)
			continue
		}

		if _, ok := obj.(*types.TypeName); !ok {
			log.Printf("警告: %s 不是一个类型", typeName)
			continue
		}

		structType, ok := obj.Type().Underlying().(*types.Struct)
		if !ok {
			log.Printf("警告: %s 不是一个结构体", typeName)
			continue
		}

		g.data[typeName] = g.extractFields(structType)
	}
}

func (g *Generator) extractFields(st *types.Struct) []FieldInfo {
	directFields := make(map[string]struct{})
	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		if !field.Anonymous() && field.Exported() {
			directFields[field.Name()] = struct{}{}
		}
	}

	var fields []FieldInfo
	seenFields := make(map[string]struct{})

	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		tag := st.Tag(i)

		if field.Anonymous() {
			embeddedType := field.Type()
			if ptr, ok := embeddedType.(*types.Pointer); ok {
				embeddedType = ptr.Elem()
			}

			if embeddedStruct, ok := embeddedType.Underlying().(*types.Struct); ok {
				subFields := g.extractFields(embeddedStruct)
				for _, subField := range subFields {
					if _, direct := directFields[subField.FieldName]; !direct {
						if _, seen := seenFields[subField.FieldName]; !seen {
							fields = append(fields, subField)
							seenFields[subField.FieldName] = struct{}{}
						}
					}
				}
			}
			continue
		}

		if !field.Exported() {
			continue
		}

		fieldName := field.Name()

		if _, seen := seenFields[fieldName]; seen {
			continue
		}

		columnName := namingStrategy.ColumnName("", fieldName)

		if tag != "" {
			structTag := reflect.StructTag(strings.Trim(tag, "`"))
			if gormTag := structTag.Get("gorm"); gormTag != "" {
				settings := schema.ParseTagSetting(gormTag, ";")
				if col, ok := settings["COLUMN"]; ok {
					columnName = col
				}
			}
		}

		fields = append(fields, FieldInfo{
			FieldName:  fieldName,
			ColumnName: columnName,
		})
		seenFields[fieldName] = struct{}{}
	}
	return fields
}

func (g *Generator) generate() {
	if len(g.data) == 0 {
		return
	}

	f := jen.NewFile(g.pkgName)
	f.HeaderComment("Code generated by gen-props. DO NOT EDIT.")

	queryPkg := "github.com/im-wmkong/gorm-query/query"

	for typeName, fields := range g.data {
		// 生成小写的结构体名称，例如: userProps
		propTypeName := strings.ToLower(typeName[:1]) + typeName[1:] + "Props"

		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", typeName, typeName))

		// 1. 批量生成私有常量 (避免字符串硬编码重复)
		f.Const().DefsFunc(func(grp *jen.Group) {
			for _, field := range fields {
				grp.Id(propTypeName + "_" + field.FieldName).Op("=").Lit(field.ColumnName)
			}
		})

		// 2. 构建结构体类型定义
		var structFields []jen.Code
		for _, field := range fields {
			structFields = append(structFields, jen.Id(field.FieldName).Qual(queryPkg, "Column"))
		}
		f.Type().Id(propTypeName).Struct(structFields...)

		// 3. 构建 Alias(alias string) 方法，安全拼接常量
		f.Func().Params(jen.Id("p").Id(propTypeName)).Id("Alias").Params(jen.Id("alias").String()).Id(propTypeName).Block(
			jen.Return(jen.Id(propTypeName).Values(jen.DictFunc(func(d jen.Dict) {
				for _, field := range fields {
					constName := propTypeName + "_" + field.FieldName
					d[jen.Id(field.FieldName)] = jen.Qual(queryPkg, "Column").Call(
						jen.Id("alias").Op("+").Lit(".").Op("+").Id(constName),
					)
				}
			}))),
		)

		// 4. 声明全局变量，复用常量
		f.Var().Id(typeName + "Props").Op("=").Id(propTypeName).Values(jen.DictFunc(func(d jen.Dict) {
			for _, field := range fields {
				constName := propTypeName + "_" + field.FieldName
				d[jen.Id(field.FieldName)] = jen.Id(constName)
			}
		}))
	}

	err := f.Save(g.outputPath)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
	log.Printf("generated %s", g.outputPath)
}
