package main

import (
	"fmt"
	"go/types"
	"log"
	"reflect"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
	"gorm.io/gorm/schema"
)

type FieldInfo struct {
	FieldName  string
	ColumnName string
}

type Generator struct {
	pkgName    string
	data       map[string][]FieldInfo // TypeName -> Fields
	outputPath string
}

func (g *Generator) processTypes(pkg *packages.Package) {
	typesList := strings.Split(*typeNames, ",")
	for _, typeName := range typesList {
		obj := pkg.Types.Scope().Lookup(typeName)
		if obj == nil {
			log.Printf("警告: 在包 %s 中未找到类型 %s", pkg.Name, typeName)
			continue
		}

		if _, ok := obj.(*types.TypeName); !ok {
			log.Printf("警告: %s 不是一个类型", typeName)
			continue
		}

		structType, ok := obj.Type().Underlying().(*types.Struct)
		if !ok {
			log.Printf("警告: %s 不是一个结构体", typeName)
			continue
		}

		g.data[typeName] = g.extractFields(structType)
	}
}

func (g *Generator) extractFields(st *types.Struct) []FieldInfo {
	directFields := make(map[string]struct{})
	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		if !field.Anonymous() && field.Exported() {
			directFields[field.Name()] = struct{}{}
		}
	}

	var fields []FieldInfo
	seenFields := make(map[string]struct{})

	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		tag := st.Tag(i)

		if field.Anonymous() {
			embeddedType := field.Type()
			if ptr, ok := embeddedType.(*types.Pointer); ok {
				embeddedType = ptr.Elem()
			}

			if embeddedStruct, ok := embeddedType.Underlying().(*types.Struct); ok {
				subFields := g.extractFields(embeddedStruct)
				for _, subField := range subFields {
					if _, direct := directFields[subField.FieldName]; !direct {
						if _, seen := seenFields[subField.FieldName]; !seen {
							fields = append(fields, subField)
							seenFields[subField.FieldName] = struct{}{}
						}
					}
				}
			}
			continue
		}

		if !field.Exported() {
			continue
		}

		fieldName := field.Name()

		if _, seen := seenFields[fieldName]; seen {
			continue
		}

		columnName := namingStrategy.ColumnName("", fieldName)

		if tag != "" {
			structTag := reflect.StructTag(strings.Trim(tag, "`"))
			if gormTag := structTag.Get("gorm"); gormTag != "" {
				settings := schema.ParseTagSetting(gormTag, ";")
				if col, ok := settings["COLUMN"]; ok {
					columnName = col
				}
			}
		}

		fields = append(fields, FieldInfo{
			FieldName:  fieldName,
			ColumnName: columnName,
		})
		seenFields[fieldName] = struct{}{}
	}
	return fields
}

func (g *Generator) generate() {
	if len(g.data) == 0 {
		return
	}

	f := jen.NewFile(g.pkgName)
	f.HeaderComment("Code generated by gen-props. DO NOT EDIT.")

	queryPkg := "github.com/im-wmkong/gorm-query/query"

	for typeName, fields := range g.data {
		f.Comment(fmt.Sprintf("%sProps defines the fields for %s", typeName, typeName))

		// 直接声明匿名结构体变量，避免额外生成常量和内部类型
		f.Var().Id(typeName + "Props").Op("=").StructFunc(func(grp *jen.Group) {
			for _, field := range fields {
				grp.Id(field.FieldName).Qual(queryPkg, "Column")
			}
		}).CustomFunc(jen.Options{Open: "{", Close: "}", Separator: ",", Multi: true}, func(grp *jen.Group) {
			for _, field := range fields {
				grp.Id(field.FieldName).Op(":").Lit(field.ColumnName)
			}
		})
	}

	err := f.Save(g.outputPath)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
	log.Printf("generated %s", g.outputPath)
}
