// Code generated by gen-props. DO NOT EDIT.

package model

import query "github.com/im-wmkong/gorm-query/query"

// UserProps defines the fields for User
const (
	userProps_ID        = "id"
	userProps_CreatedAt = "created_at"
	userProps_UpdatedAt = "updated_at"
	userProps_DeletedAt = "deleted_at"
	userProps_UserName  = "user_name"
	userProps_Email     = "email"
	userProps_Age       = "age"
	userProps_Status    = "status"
)

type userProps struct {
	ID        query.Column
	CreatedAt query.Column
	UpdatedAt query.Column
	DeletedAt query.Column
	UserName  query.Column
	Email     query.Column
	Age       query.Column
	Status    query.Column
}

func (p userProps) Alias(alias string) userProps {
	return userProps{
		Age:       query.Column(alias + "." + userProps_Age),
		CreatedAt: query.Column(alias + "." + userProps_CreatedAt),
		DeletedAt: query.Column(alias + "." + userProps_DeletedAt),
		Email:     query.Column(alias + "." + userProps_Email),
		ID:        query.Column(alias + "." + userProps_ID),
		Status:    query.Column(alias + "." + userProps_Status),
		UpdatedAt: query.Column(alias + "." + userProps_UpdatedAt),
		UserName:  query.Column(alias + "." + userProps_UserName),
	}
}

var UserProps = userProps{
	Age:       userProps_Age,
	CreatedAt: userProps_CreatedAt,
	DeletedAt: userProps_DeletedAt,
	Email:     userProps_Email,
	ID:        userProps_ID,
	Status:    userProps_Status,
	UpdatedAt: userProps_UpdatedAt,
	UserName:  userProps_UserName,
}
