package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMain_GeneratesSchemaFile(t *testing.T) {
	originalWD, err := os.Getwd()
	require.NoError(t, err)

	workDir := t.TempDir()
	require.NoError(t, os.Chdir(workDir))
	defer func() {
		require.NoError(t, os.Chdir(originalWD))
	}()

	main()

	content, err := os.ReadFile(filepath.Join(workDir, "schema", "user_gen.go"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, string(content), "package schema")
	assert.Contains(t, string(content), "var User = user{")
}

func TestMain_FailsInMismatchedPackageDir(t *testing.T) {
	if os.Getenv("BE_CRASHER") == "1" {
		main()
		return
	}

	dir := t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(dir, "schema"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "schema", "existing.go"), []byte("package otherpkg\n"), 0o644))

	cmd := exec.Command(os.Args[0], "-test.run=TestMain_FailsInMismatchedPackageDir")
	cmd.Env = append(os.Environ(), "BE_CRASHER=1")
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	err := cmd.Run()
	require.Error(t, err)
	assert.Contains(t, stderr.String(), "package mismatch")
}
