package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMain_GeneratesSchemaFile(t *testing.T) {
	originalWD, err := os.Getwd()
	require.NoError(t, err)

	workDir := t.TempDir()
	require.NoError(t, os.Chdir(workDir))
	defer func() {
		require.NoError(t, os.Chdir(originalWD))
	}()

	main()

	content, err := os.ReadFile(filepath.Join(workDir, "schema", "user_gen.go"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, string(content), "package schema")
	assert.Contains(t, string(content), "var User = user{")
}
