// Package colgen generates type-safe column definitions for GORM models.
//
// It parses GORM model fields via schema.Parse and generates a corresponding
// typed property dictionary. These properties can be used to build query
// conditions with a type-safe SQL-building experience.
//
// It supports a custom naming strategy and allows configuring the output package
// name. By default, it generates one file per model in the output directory.
package colgen

import (
	"bytes"
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"sync"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/fsx"
	"github.com/im-wmkong/gorm-query/internal/reflectx"
	"gorm.io/gorm/schema"
)

const queryPkg = "github.com/im-wmkong/gorm-query/query"

type Generator struct {
	cfg config
}

// New creates a new Generator.
//
// Example:
//
//	g := colgen.New(
//	    colgen.WithOutputDir("columns"),
//	)
//	_ = g
func New(opts ...Option) *Generator {
	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Generator{cfg: cfg}
}

// Generate parses the given GORM models and generates column files into outputDir.
//
// Example:
//
//	// Generate columns into the same package as the models.
//	err := colgen.New(colgen.WithOutputDir("./columns")).Generate(&model.User{})
//	_ = err
func (g *Generator) Generate(models ...any) error {
	models, nilCount := g.filterNilModels(models)
	if nilCount > 0 {
		g.cfg.logger.Debug("filtered %d nil model(s), %d remaining", nilCount, len(models))
	}

	if len(models) == 0 {
		return fmt.Errorf("no models provided")
	}

	pkgName, err := g.packageName(models)
	if err != nil {
		return err
	}

	if err := g.checkOutputDir(pkgName); err != nil {
		return err
	}

	g.cfg.logger.Info("generating columns for %d model(s)", len(models))

	schemas, err := g.schemas(models)
	if err != nil {
		return err
	}

	for _, sch := range schemas {
		content, err := g.render(sch, pkgName)
		if err != nil {
			return err
		}

		filename := filepath.Join(g.cfg.outputDir, g.modelOutputFile(sch))
		if err := g.writeFile(filename, content); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) filterNilModels(models []any) ([]any, int) {
	filtered := make([]any, 0, len(models))
	for _, model := range models {
		if model != nil {
			filtered = append(filtered, model)
		}
	}
	return filtered, len(models) - len(filtered)
}

func (g *Generator) packageName(models []any) (string, error) {
	if g.cfg.packageName != "" {
		g.cfg.logger.Debug("using explicit package name: %s", g.cfg.packageName)
		return g.cfg.packageName, nil
	}

	if outputPkg := g.outputDirPackageName(); outputPkg != "" {
		g.cfg.logger.Debug("inferred package name from output dir: %s", outputPkg)
		return outputPkg, nil
	}

	pkgName := reflectx.PackageName(models[0])
	g.cfg.logger.Debug("auto-detected package name: %s", pkgName)
	for _, model := range models[1:] {
		currentPkg := reflectx.PackageName(model)
		if currentPkg != pkgName {
			return "", fmt.Errorf("all models must be in the same package or explicitly set WithPackageName")
		}
	}

	return pkgName, nil
}

func (g *Generator) outputDirPackageName() string {
	base := filepath.Base(filepath.Clean(g.cfg.outputDir))
	if token.IsIdentifier(base) {
		return base
	}

	return ""
}

func (g *Generator) checkOutputDir(pkgName string) error {
	if err := os.MkdirAll(g.cfg.outputDir, 0755); err != nil {
		return fmt.Errorf("create output dir failed: %w", err)
	}

	fsPkg, err := fsx.PackageNameFromDir(g.cfg.outputDir)
	if err != nil {
		return fmt.Errorf("detect package failed: %w", err)
	}
	if fsPkg != "" && fsPkg != pkgName {
		return fmt.Errorf("package mismatch: outputDir has package %q, but generator uses %q", fsPkg, pkgName)
	}

	return nil
}

func (g *Generator) schemas(models []any) ([]*schema.Schema, error) {
	seen := make(map[string]struct{})
	schemaCache := &sync.Map{}
	schemas := make([]*schema.Schema, 0, len(models))

	for _, model := range models {
		sch, err := schema.Parse(model, schemaCache, g.cfg.namingStrategy)
		if err != nil {
			return nil, fmt.Errorf("gorm schema parse failed: %w", err)
		}

		if len(sch.Fields) == 0 {
			g.cfg.logger.Warn("skipping model %s: no schema fields", sch.Name)
			continue
		}

		// Deduplicate by model name.
		if _, ok := seen[sch.Name]; ok {
			g.cfg.logger.Warn("skipping duplicate model: %s", sch.Name)
			continue
		}
		seen[sch.Name] = struct{}{}

		g.cfg.logger.Debug("parsed model %s: %d field(s)", sch.Name, len(sch.Fields))
		schemas = append(schemas, sch)
	}

	return schemas, nil
}

func (g *Generator) render(sch *schema.Schema, pkgName string) ([]byte, error) {
	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by colgen. DO NOT EDIT.")
	g.gen(f, sch)

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("render failed: %w", err)
	}

	return buf.Bytes(), nil
}

func (g *Generator) gen(f *jen.File, sch *schema.Schema) {
	f.Comment(fmt.Sprintf("%s provides query columns for the %s model.", sch.Name, sch.Name))

	f.Var().Id(sch.Name).Op("=").StructFunc(func(grp *jen.Group) {
		for _, field := range sch.Fields {
			if field.DBName == "" {
				continue
			}
			grp.Id(field.Name).Qual(queryPkg, "Column")
		}
	}).CustomFunc(jen.Options{
		Open:      "{",
		Close:     "}",
		Separator: ",",
		Multi:     true,
	}, func(grp *jen.Group) {
		for _, field := range sch.Fields {
			if field.DBName == "" {
				continue
			}
			grp.Id(field.Name).Op(":").Lit(field.DBName)
		}
	})

	f.Line()
}

func (g *Generator) modelOutputFile(sch *schema.Schema) string {
	return g.cfg.namingStrategy.ColumnName("", sch.Name) + "_gen.go"
}

func (g *Generator) writeFile(filename string, content []byte) error {
	if g.cfg.dryRun {
		old, _ := os.ReadFile(filename)
		if !bytes.Equal(old, content) {
			return fmt.Errorf("generated file outdated: %s", filename)
		}
		g.cfg.logger.Info("dry-run passed: %s is up to date", filename)
		return nil
	}

	if old, err := os.ReadFile(filename); err == nil {
		if bytes.Equal(old, content) {
			g.cfg.logger.Debug("skipped writing %s: content unchanged", filename)
			return nil
		}
	}

	if err := os.WriteFile(filename, content, 0644); err != nil {
		return fmt.Errorf("write file failed: %w", err)
	}

	g.cfg.logger.Info("generated %s", filename)

	return nil
}
