// Code generated by schemagen. DO NOT EDIT.

package schema

import query "github.com/im-wmkong/gorm-query/query"

// Profile provides query columns and associations for the Profile model.
var Profile = struct {
	ID        query.Column
	CreatedAt query.Column
	UpdatedAt query.Column
	DeletedAt query.Column
	UserID    query.Column
	Bio       query.Column
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	UserID:    "user_id",
	Bio:       "bio",
}
