package schemagen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/codegen"
	"github.com/im-wmkong/gorm-query/internal/gormx"
	"gorm.io/gorm/schema"
)

// queryMethodName is the name of the method generated to expose a typed
// query.Builder for the model. It also drives the "Query" collision check
// against fields and associations on the model.
const queryMethodName = "Query"

// Renderer turns one parsed *schema.Schema into a ready-to-write Go
// source file.
type Renderer struct {
	cfg       config
	schema    *schema.Schema
	pkgName   string
	typeName  string
	tableName string
	relations []gormx.Relation
	members   []member
}

type member struct {
	name     string
	path     []string
	depth    int
	typeCode jen.Code
	ctorCode jen.Code
}

func newRenderer(cfg config, sch *schema.Schema, pkgName string) *Renderer {
	return &Renderer{
		cfg:       cfg,
		schema:    sch,
		pkgName:   pkgName,
		typeName:  codegen.UnexportName(sch.Name),
		tableName: gormx.TableName(sch, cfg.namingStrategy),
		relations: gormx.OrderedRelations(sch),
	}
}

// Render produces the formatted Go source for the schema.
func (r *Renderer) Render() ([]byte, error) {
	if err := r.prepareMembers(); err != nil {
		return nil, err
	}
	f := jen.NewFile(r.pkgName)
	f.HeaderComment("Code generated by schemagen. DO NOT EDIT.")

	r.writeStructDecl(f)
	r.writeVarDecl(f)
	if r.hasQueryCollision() {
		r.cfg.logger.Debug("skipping Query() for %s: collides with an existing field or relation", r.schema.Name)
	} else {
		r.writeQueryMethod(f)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("render failed: %w", err)
	}
	return buf.Bytes(), nil
}

// writeStructDecl writes the unexported struct that lists every column and
// association of the model.
func (r *Renderer) writeStructDecl(f *jen.File) {
	f.Commentf("%s describes the schema metadata for the %s model.", r.typeName, r.schema.Name)
	f.Type().Id(r.typeName).StructFunc(func(grp *jen.Group) {
		r.eachMember(func(name string, typeCode, _ jen.Code) {
			grp.Id(name).Add(typeCode)
		})
	})
	f.Line()
}

// writeVarDecl writes the package-level variable that materialises every
// column and association as a typed value.
func (r *Renderer) writeVarDecl(f *jen.File) {
	f.Commentf("%s provides query columns and associations for the %s model.", r.schema.Name, r.schema.Name)
	f.Var().Id(r.schema.Name).Op("=").Id(r.typeName).CustomFunc(jen.Options{
		Open:      "{",
		Close:     "}",
		Separator: ",",
		Multi:     true,
	}, func(grp *jen.Group) {
		r.eachMember(func(name string, _, ctorCode jen.Code) {
			grp.Id(name).Op(":").Add(ctorCode)
		})
	})
	f.Line()
}

// writeQueryMethod writes "func (s *<type>) Query() *query.Builder[Model]".
func (r *Renderer) writeQueryMethod(f *jen.File) {
	parent := codegen.GoTypeCode(r.schema.ModelType)
	f.Commentf("%s returns a new query builder bound to the %s model.", queryMethodName, r.schema.ModelType.Name())
	f.Func().
		Params(jen.Id("s").Op("*").Id(r.typeName)).
		Id(queryMethodName).
		Params().
		Op("*").Qual(codegen.QueryPkg, "Builder").Types(parent).
		Block(jen.Return(jen.Qual(codegen.QueryPkg, "New").Types(parent).Call()))
	f.Line()
}

// eachMember iterates over every generated member (column then association),
// invoking fn with the member name, its type expression, and its constructor
// expression. Columns whose DBName is empty (e.g. gorm:"-") are skipped.
func (r *Renderer) eachMember(fn func(name string, typeCode, ctorCode jen.Code)) {
	for _, member := range r.members {
		fn(member.name, member.typeCode, member.ctorCode)
	}
}

// prepareMembers shares column and association names between declarations,
// initializers and the Query method's collision check.
func (r *Renderer) prepareMembers() error {
	r.members = nil
	parent := r.schema.ModelType
	for _, field := range r.schema.Fields {
		if field.DBName == "" || r.schema.FieldsByDBName[field.DBName] != field {
			continue
		}
		r.members = append(r.members, member{
			name:     field.Name,
			path:     field.BindNames,
			depth:    1,
			typeCode: codegen.ColumnTypeCode(field.FieldType),
			ctorCode: codegen.ColumnCtorCode(field.FieldType, r.tableName, field.DBName),
		})
	}
	for _, rel := range r.relations {
		r.members = append(r.members, member{
			name:     rel.Name,
			path:     []string{rel.Name},
			depth:    1,
			typeCode: codegen.AssociationTypeCode(parent, rel.ChildType),
			ctorCode: codegen.AssociationCtorCode(parent, rel.ChildType, rel.Name),
		})
	}
	return r.resolveMemberNames()
}

// resolveMemberNames adds only as much of the embedded field path as needed
// to distinguish names, without depending on field declaration order.
func (r *Renderer) resolveMemberNames() error {
	for {
		counts := make(map[string]int, len(r.members))
		for _, m := range r.members {
			counts[m.name]++
		}
		var conflict string
		changed := false
		for i := range r.members {
			m := &r.members[i]
			if counts[m.name] < 2 {
				continue
			}
			conflict = m.name
			if m.depth < len(m.path) {
				m.depth++
				m.name = strings.Join(m.path[len(m.path)-m.depth:], "")
				changed = true
			}
		}
		if conflict == "" {
			return nil
		}
		if !changed {
			var paths []string
			for _, m := range r.members {
				if m.name == conflict {
					paths = append(paths, strings.Join(m.path, "."))
				}
			}
			return fmt.Errorf("member collision in %s: %q from %s", r.schema.Name, conflict, strings.Join(paths, ", "))
		}
	}
}

// hasQueryCollision reports whether the model already declares a field or
// association named queryMethodName, in which case the generated method
// would shadow it and is therefore omitted.
func (r *Renderer) hasQueryCollision() bool {
	for _, m := range r.members {
		if m.name == queryMethodName {
			return true
		}
	}
	return false
}
