package schemagen

import (
	"bytes"
	"fmt"

	"github.com/dave/jennifer/jen"
	"github.com/im-wmkong/gorm-query/internal/codegen"
	"github.com/im-wmkong/gorm-query/internal/gormx"
	"gorm.io/gorm/schema"
)

// queryMethodName is the name of the method generated to expose a typed
// query.Builder for the model. It also drives the "Query" collision check
// against fields and associations on the model.
const queryMethodName = "Query"

// Renderer turns one parsed *schema.Schema into a ready-to-write Go
// source file.
type Renderer struct {
	cfg       config
	schema    *schema.Schema
	pkgName   string
	typeName  string
	tableName string
	relations []gormx.Relation
}

func newRenderer(cfg config, sch *schema.Schema, pkgName string) *Renderer {
	return &Renderer{
		cfg:       cfg,
		schema:    sch,
		pkgName:   pkgName,
		typeName:  codegen.UnexportName(sch.Name),
		tableName: gormx.TableName(sch, cfg.namingStrategy),
		relations: gormx.OrderedRelations(sch),
	}
}

// Render produces the formatted Go source for the schema.
func (r *Renderer) Render() ([]byte, error) {
	f := jen.NewFile(r.pkgName)
	f.HeaderComment("Code generated by schemagen. DO NOT EDIT.")

	r.writeStructDecl(f)
	r.writeVarDecl(f)
	if r.hasQueryCollision() {
		r.cfg.logger.Debug("skipping Query() for %s: collides with an existing field or relation", r.schema.Name)
	} else {
		r.writeQueryMethod(f)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("render failed: %w", err)
	}
	return buf.Bytes(), nil
}

// writeStructDecl writes the unexported struct that lists every column and
// association of the model.
func (r *Renderer) writeStructDecl(f *jen.File) {
	f.Commentf("%s describes the schema metadata for the %s model.", r.typeName, r.schema.Name)
	f.Type().Id(r.typeName).StructFunc(func(grp *jen.Group) {
		r.eachMember(func(name string, typeCode, _ jen.Code) {
			grp.Id(name).Add(typeCode)
		})
	})
	f.Line()
}

// writeVarDecl writes the package-level variable that materialises every
// column and association as a typed value.
func (r *Renderer) writeVarDecl(f *jen.File) {
	f.Commentf("%s provides query columns and associations for the %s model.", r.schema.Name, r.schema.Name)
	f.Var().Id(r.schema.Name).Op("=").Id(r.typeName).CustomFunc(jen.Options{
		Open:      "{",
		Close:     "}",
		Separator: ",",
		Multi:     true,
	}, func(grp *jen.Group) {
		r.eachMember(func(name string, _, ctorCode jen.Code) {
			grp.Id(name).Op(":").Add(ctorCode)
		})
	})
	f.Line()
}

// writeQueryMethod writes "func (s *<type>) Query() *query.Builder[Model]".
func (r *Renderer) writeQueryMethod(f *jen.File) {
	parent := codegen.GoTypeCode(r.schema.ModelType)
	f.Commentf("%s returns a new query builder bound to the %s model.", queryMethodName, r.schema.ModelType.Name())
	f.Func().
		Params(jen.Id("s").Op("*").Id(r.typeName)).
		Id(queryMethodName).
		Params().
		Op("*").Qual(codegen.QueryPkg, "Builder").Types(parent).
		Block(jen.Return(jen.Qual(codegen.QueryPkg, "New").Types(parent).Call()))
	f.Line()
}

// eachMember iterates over every generated member (column then association),
// invoking fn with the member name, its type expression, and its constructor
// expression. Columns whose DBName is empty (e.g. gorm:"-") are skipped.
func (r *Renderer) eachMember(fn func(name string, typeCode, ctorCode jen.Code)) {
	parent := r.schema.ModelType
	for _, field := range r.schema.Fields {
		if field.DBName == "" {
			continue
		}
		fn(
			field.Name,
			codegen.ColumnTypeCode(field.FieldType),
			codegen.ColumnCtorCode(field.FieldType, r.tableName, field.DBName),
		)
	}
	for _, rel := range r.relations {
		fn(
			rel.Name,
			codegen.AssociationTypeCode(parent, rel.ChildType),
			codegen.AssociationCtorCode(parent, rel.ChildType, rel.Name),
		)
	}
}

// hasQueryCollision reports whether the model already declares a field or
// association named queryMethodName, in which case the generated method
// would shadow it and is therefore omitted.
func (r *Renderer) hasQueryCollision() bool {
	for _, field := range r.schema.Fields {
		if field.Name == queryMethodName {
			return true
		}
	}
	for _, rel := range r.relations {
		if rel.Name == queryMethodName {
			return true
		}
	}
	return false
}
