package schemagen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/im-wmkong/gorm-query/example/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type User struct {
	gorm.Model
	UserName string `gorm:"column:user_name;size:255;not null"`
	Email    string `gorm:"column:email;size:255;unique"`
	Age      int    `gorm:"column:age"`
	Status   int    `gorm:"column:status;default:1"` // 1: active, 0: inactive
}

type LocalSchemaModel struct {
	ID uint
}

type EmptySchemaModel struct{}

type unexportedSchemaModel struct {
	ID uint
}

func TestGenerateSchema_SuccessAndIdempotent(t *testing.T) {
	outDir := t.TempDir()

	g := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
		WithLogger(nil),
	)

	err := g.Generate(nil, &User{}, &User{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, generated, "package schemagen")

	err = g.Generate(&User{})
	require.NoError(t, err)
	again, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)
	assert.Equal(t, content, again, "regeneration must preserve file content")
}

func TestGenerateSchema_WithExplicitPackageNameForMixedModels(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
	).Generate(&User{}, &LocalSchemaModel{})
	require.NoError(t, err)

	userContent, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)
	localContent, err := os.ReadFile(filepath.Join(outDir, "local_schema_model_gen.go"))
	require.NoError(t, err)

	assert.Contains(t, string(userContent), "package schemagen")
	assert.Contains(t, string(localContent), "package schemagen")
	assert.NotEqual(t, string(userContent), string(localContent))
}

func TestGenerateSchema_SkipsModelsWithoutSchemaFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
	).Generate(&EmptySchemaModel{})
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "empty_schema_model_gen.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestGenerateSchema_SkipsUnexportedModels(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
		WithLogger(nil),
	).Generate(&unexportedSchemaModel{})
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "unexported_schema_model_gen.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestGenerateSchema_DryRun(t *testing.T) {
	outDir := t.TempDir()

	g := New(WithOutputDir(outDir), WithPackageName("schemagen"))
	require.NoError(t, g.Generate(&User{}))

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithDryRun(true),
	)
	require.NoError(t, dryRunGenerator.Generate(&User{}))

	generatedFile := filepath.Join(outDir, "user_gen.go")
	// Overwrite the generated file with different content so dry-run detects it's outdated.
	require.NoError(t, os.WriteFile(generatedFile, []byte("package schemagen\n"), 0644))

	err := dryRunGenerator.Generate(&User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file outdated")
	assert.Contains(t, err.Error(), generatedFile)
}

func TestGenerateSchema_DryRunMissingFile(t *testing.T) {
	outDir := t.TempDir()

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithDryRun(true),
	)

	err := dryRunGenerator.Generate(&User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file missing")
	assert.Contains(t, err.Error(), filepath.Join(outDir, "user_gen.go"))
}

func TestGenerateSchema_ErrorScenarios(t *testing.T) {
	t.Run("no models", func(t *testing.T) {
		err := New().Generate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no models provided")
	})

	t.Run("models from different packages", func(t *testing.T) {
		err := New(WithOutputDir(t.TempDir()), WithPackageName("schema")).Generate(&User{}, &model.User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "all models must be in the same package")
	})

	t.Run("package mismatch in output dir", func(t *testing.T) {
		outDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(outDir, "existing.go"), []byte("// generated elsewhere\n\npackage otherpkg\n"), 0644))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "package mismatch")
	})

	t.Run("create output dir failed", func(t *testing.T) {
		baseDir := t.TempDir()
		blockedPath := filepath.Join(baseDir, "blocked")
		require.NoError(t, os.WriteFile(blockedPath, []byte("not a directory"), 0644))

		err := New(WithOutputDir(blockedPath)).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "create output dir failed")
	})

	t.Run("schema parse failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("broken"),
		).Generate(123)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "gorm schema parse failed")
	})

	t.Run("invalid package name", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("invalid-package"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "invalid package name")
	})

	t.Run("package name resolution failed", func(t *testing.T) {
		// outputDir ends with an invalid Go identifier and no explicit package name,
		// so packageName() returns an error.
		outDir := filepath.Join(t.TempDir(), "invalid-dir")
		require.NoError(t, os.MkdirAll(outDir, 0755))

		err := New(WithOutputDir(outDir)).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unable to resolve package name")
	})

	t.Run("target path is a directory", func(t *testing.T) {
		outDir := t.TempDir()
		// Create a directory at the target file path so both os.ReadFile and os.WriteFile fail.
		require.NoError(t, os.Mkdir(filepath.Join(outDir, "user_gen.go"), 0755))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "read existing file")
		assert.Contains(t, err.Error(), "failed")
	})
}

// QueryCollisionModel intentionally declares a "Query" field so the generator
// detects a collision and skips emitting the typed Query() helper.
type QueryCollisionModel struct {
	ID    uint
	Query string `gorm:"column:query"`
}

func TestGenerateSchema_SkipsQueryWhenFieldCollides(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithLogger(nil),
	).Generate(&QueryCollisionModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "query_collision_model_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "type queryCollisionModel struct")
	assert.NotContains(t, generated, ") Query() *query.Builder[")
}

// QueryRelationCollisionParent declares an association named "Query"; the
// generator must detect the collision through the relation list (not just
// the field list) and omit the Query() helper.
type QueryRelationCollisionParent struct {
	ID    uint
	Query QueryRelationCollisionChild `gorm:"foreignKey:ParentID"`
}

type QueryRelationCollisionChild struct {
	ID       uint
	ParentID uint
}

func TestGenerateSchema_SkipsQueryWhenRelationCollides(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
	).Generate(&QueryRelationCollisionParent{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "query_relation_collision_parent_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "type queryRelationCollisionParent struct")
	assert.NotContains(t, generated, ") Query() *query.Builder[")
}

// IgnoredFieldRelationParent keeps its association while excluding the ignored field.
type IgnoredFieldRelationParent struct {
	ID       uint
	Ignored  string                      `gorm:"-"`
	Children []IgnoredFieldRelationChild `gorm:"foreignKey:ParentID"`
}

type IgnoredFieldRelationChild struct {
	ID       uint
	ParentID uint
}

func TestGenerateSchema_HandlesIgnoredFieldsAndRelations(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
	).Generate(&IgnoredFieldRelationParent{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "ignored_field_relation_parent_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.NotContains(t, generated, "Ignored ")
	assert.Contains(t, generated, "Children query.Association[")
}
