package schemagen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/im-wmkong/gorm-query/example/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type User struct {
	gorm.Model
	UserName string `gorm:"column:user_name;size:255;not null"`
	Email    string `gorm:"column:email;size:255;unique"`
	Age      int    `gorm:"column:age"`
	Status   int    `gorm:"column:status;default:1"` // 1: active, 0: inactive
}

type LocalSchemaModel struct {
	ID uint
}

type EmptySchemaModel struct{}

type PartiallyIgnoredSchemaModel struct {
	ID      uint
	Name    string `gorm:"column:name"`
	Ignored string `gorm:"-"`
}

type unexportedSchemaModel struct {
	ID uint
}

type testLogger struct {
	infoCalls  int
	debugCalls int
	warnCalls  int
}

func (l *testLogger) Debug(string, ...any) { l.debugCalls++ }
func (l *testLogger) Info(string, ...any)  { l.infoCalls++ }
func (l *testLogger) Warn(string, ...any)  { l.warnCalls++ }

func TestFilterNilModels(t *testing.T) {
	filtered, nilCount := New().filterNilModels([]any{nil, &User{}, nil, &LocalSchemaModel{}})
	require.Len(t, filtered, 2)
	assert.Equal(t, 2, nilCount)
	assert.IsType(t, &User{}, filtered[0])
	assert.IsType(t, &LocalSchemaModel{}, filtered[1])
}

func TestGeneratorResolvePackageName(t *testing.T) {
	t.Run("explicit package name wins", func(t *testing.T) {
		g := New(WithPackageName("model"))
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "model", pkgName)
	})

	t.Run("inferred from default output dir", func(t *testing.T) {
		g := New()
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "schema", pkgName)
	})

	t.Run("inferred from custom output dir", func(t *testing.T) {
		g := New(WithOutputDir("./path/to/mypkg"))
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "mypkg", pkgName)
	})

	t.Run("fails when output dir is not a valid identifier", func(t *testing.T) {
		g := New(WithOutputDir("./invalid-dir"))
		_, err := g.packageName()
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unable to resolve package name")
	})
}

func TestGeneratorCheckSameModelPackage(t *testing.T) {
	g := New()

	t.Run("single model passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage([]any{&User{}}))
	})

	t.Run("empty slice passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage(nil))
	})

	t.Run("same package passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage([]any{&User{}, &LocalSchemaModel{}}))
	})

	t.Run("anonymous struct fails with no package path", func(t *testing.T) {
		err := g.checkSamePackage([]any{&User{}, &struct{ ID uint }{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("first model has no package path", func(t *testing.T) {
		err := g.checkSamePackage([]any{&struct{ ID uint }{}, &User{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("different real packages fail", func(t *testing.T) {
		// schemagen.User and example/model.User live in different real packages.
		err := g.checkSamePackage([]any{&User{}, &model.User{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "all models must be in the same package")
	})
}

func TestGenerateSchema_SuccessAndIdempotent(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "ignored_test.go"), []byte("package ignored\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "notes.txt"), []byte("plain text"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "invalid.go"), []byte("var broken = 1\n"), 0644))
	require.NoError(t, os.Mkdir(filepath.Join(outDir, "nested"), 0755))
	require.NoError(t, os.Symlink(filepath.Join(outDir, "missing.go"), filepath.Join(outDir, "broken_link.go")))

	tl := &testLogger{}
	g := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
		WithLogger(tl),
	)

	err := g.Generate(&User{}, &User{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, generated, "package schemagen")
	assert.Contains(t, generated, "type user struct")
	assert.Contains(t, generated, "var User = user{")
	assert.Contains(t, generated, "UserName")
	assert.Contains(t, generated, "query.StringColumn[string]")
	assert.Contains(t, generated, "DeletedAt query.ValueColumn[gorm.DeletedAt]")
	assert.Contains(t, generated, `query.NewStringColumn[string]("user", "user_name")`)
	assert.Contains(t, generated, `query "github.com/im-wmkong/gorm-query/query"`)
	assert.Contains(t, generated, ") Query() *query.Builder[")

	// First run: Info contains "generating schema..." and "generated ...".
	assert.Equal(t, 2, tl.infoCalls)
	// Duplicate User triggers one Warn.
	assert.Equal(t, 1, tl.warnCalls)
	assert.Greater(t, tl.debugCalls, 0)

	prevInfo := tl.infoCalls
	err = g.Generate(&User{})
	require.NoError(t, err)
	// Idempotent: unchanged content skips writing; only Debug is emitted.
	// Info should not increase except "generating schema...".
	assert.Equal(t, prevInfo+1, tl.infoCalls)
}

func TestGenerateSchema_DefaultLayoutMatchesSchemaPackage(t *testing.T) {
	workDir := t.TempDir()

	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(workDir))
	t.Cleanup(func() {
		require.NoError(t, os.Chdir(originalWD))
	})

	err = New().Generate(&User{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(workDir, "schema", "user_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "package schema")
	assert.Contains(t, generated, "type user struct")
	assert.Contains(t, generated, "var User = user{")
	assert.Contains(t, generated, "UserName  query.StringColumn[string]")
	assert.Contains(t, generated, `query.NewStringColumn[string]("user", "user_name")`)
}

func TestGenerateSchema_WithExplicitPackageNameForMixedModels(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
	).Generate(&User{}, &LocalSchemaModel{})
	require.NoError(t, err)

	userContent, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)
	localContent, err := os.ReadFile(filepath.Join(outDir, "local_schema_model_gen.go"))
	require.NoError(t, err)

	assert.Contains(t, string(userContent), "User provides query columns and associations for the User model.")
	assert.Contains(t, string(userContent), "var User = user{")
	assert.Contains(t, string(localContent), "LocalSchemaModel provides query columns and associations for the LocalSchemaModel model.")
	assert.Contains(t, string(localContent), "var LocalSchemaModel = localSchemaModel{")
	assert.Contains(t, string(localContent), `query.NewNumericColumn[uint]("local_schema_model", "id")`)
}

func TestGenerateSchema_SkipsModelsWithoutSchemaFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
	).Generate(&EmptySchemaModel{})
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "empty_schema_model_gen.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestGenerateSchema_SkipsUnexportedModels(t *testing.T) {
	outDir := t.TempDir()

	tl := &testLogger{}
	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
		WithLogger(tl),
	).Generate(&unexportedSchemaModel{})
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "unexported_schema_model_gen.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
	assert.Equal(t, 1, tl.warnCalls)
}

func TestGenerateSchema_SkipsIgnoredFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
	).Generate(&PartiallyIgnoredSchemaModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "partially_ignored_schema_model_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "PartiallyIgnoredSchemaModel provides query columns and associations for the PartiallyIgnoredSchemaModel model.")
	assert.Contains(t, generated, "ID:")
	assert.Contains(t, generated, "Name query.StringColumn[string]")
	assert.NotContains(t, generated, "Ignored query.")
	assert.NotContains(t, generated, `"ignored"`)
}

func TestGenerateSchema_DryRun(t *testing.T) {
	outDir := t.TempDir()

	g := New(WithOutputDir(outDir), WithPackageName("schemagen"))
	require.NoError(t, g.Generate(&User{}))

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithDryRun(true),
	)
	require.NoError(t, dryRunGenerator.Generate(&User{}))

	generatedFile := filepath.Join(outDir, "user_gen.go")
	// Overwrite the generated file with different content so dry-run detects it's outdated.
	require.NoError(t, os.WriteFile(generatedFile, []byte("package schemagen\n"), 0644))

	err := dryRunGenerator.Generate(&User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file outdated")
	assert.Contains(t, err.Error(), generatedFile)
}

func TestGenerateSchema_DryRunMissingFile(t *testing.T) {
	outDir := t.TempDir()

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithDryRun(true),
	)

	err := dryRunGenerator.Generate(&User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file missing")
	assert.Contains(t, err.Error(), filepath.Join(outDir, "user_gen.go"))
}

func TestGenerateSchema_ErrorScenarios(t *testing.T) {
	t.Run("no models", func(t *testing.T) {
		err := New().Generate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no models provided")
	})

	t.Run("WithLogger nil does not panic", func(t *testing.T) {
		g := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("schemagen"),
			WithLogger(nil),
		)
		err := g.Generate(&User{})
		require.NoError(t, err)
	})

	t.Run("mixed packages without explicit package name", func(t *testing.T) {
		// Use an anonymous struct as the second arg (reflect.Type.PkgPath() == "") to trigger
		// the "no package path" validation without depending on example/model.
		err := New(WithOutputDir(t.TempDir())).Generate(&User{}, &struct{ ID uint }{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("package mismatch in output dir", func(t *testing.T) {
		outDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(outDir, "existing.go"), []byte("// generated elsewhere\n\npackage otherpkg\n"), 0644))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "package mismatch")
	})

	t.Run("create output dir failed", func(t *testing.T) {
		baseDir := t.TempDir()
		blockedPath := filepath.Join(baseDir, "blocked")
		require.NoError(t, os.WriteFile(blockedPath, []byte("not a directory"), 0644))

		err := New(WithOutputDir(blockedPath)).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "create output dir failed")
	})

	t.Run("detect package failed", func(t *testing.T) {
		outDir := filepath.Join(t.TempDir(), "locked")
		require.NoError(t, os.Mkdir(outDir, 0000))
		t.Cleanup(func() {
			require.NoError(t, os.Chmod(outDir, 0755))
		})

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "detect package failed")
	})

	t.Run("schema parse failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("broken"),
		).Generate(123)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "gorm schema parse failed")
	})

	t.Run("render failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("invalid-package"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "render failed")
	})

	t.Run("package name resolution failed", func(t *testing.T) {
		// outputDir ends with an invalid Go identifier and no explicit package name,
		// so packageName() returns an error.
		outDir := filepath.Join(t.TempDir(), "invalid-dir")
		require.NoError(t, os.MkdirAll(outDir, 0755))

		err := New(WithOutputDir(outDir)).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unable to resolve package name")
	})

	t.Run("target path is a directory", func(t *testing.T) {
		outDir := t.TempDir()
		// Create a directory at the target file path so both os.ReadFile and os.WriteFile fail.
		require.NoError(t, os.Mkdir(filepath.Join(outDir, "user_gen.go"), 0755))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "read existing file")
		assert.Contains(t, err.Error(), "failed")
	})

	t.Run("write file failed on read-only dir", func(t *testing.T) {
		baseDir := t.TempDir()
		outDir := filepath.Join(baseDir, "readonly")
		require.NoError(t, os.Mkdir(outDir, 0755))
		// Make the directory read-only so os.ReadFile returns ErrNotExist (treated as "exists=false"),
		// while os.WriteFile fails with a permission error.
		require.NoError(t, os.Chmod(outDir, 0555))
		t.Cleanup(func() {
			_ = os.Chmod(outDir, 0755)
		})

		err := New(
			WithOutputDir(outDir),
			WithPackageName("schemagen"),
		).Generate(&User{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "write file")
		assert.Contains(t, err.Error(), "failed")
	})
}

func TestNopLogger_DoesNotPanic(t *testing.T) {
	l := NopLogger()
	require.NotNil(t, l)

	// no output asserted, just ensure these methods are executed
	l.Debug("debug %s", "x")
	l.Info("info %d", 1)
	l.Warn("warn %v", nil)
}

// QueryCollisionModel intentionally declares a "Query" field so the generator
// detects a collision and skips emitting the typed Query() helper.
type QueryCollisionModel struct {
	ID    uint
	Query string `gorm:"column:query"`
}

func TestGenerateSchema_SkipsQueryWhenFieldCollides(t *testing.T) {
	outDir := t.TempDir()

	tl := &testLogger{}
	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithLogger(tl),
	).Generate(&QueryCollisionModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "query_collision_model_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "type queryCollisionModel struct")
	assert.NotContains(t, generated, ") Query() *query.Builder[")
	assert.GreaterOrEqual(t, tl.debugCalls, 1)
}

// QueryRelationCollisionParent declares an association named "Query"; the
// generator must detect the collision through the relation list (not just
// the field list) and omit the Query() helper.
type QueryRelationCollisionParent struct {
	ID    uint
	Query QueryRelationCollisionChild `gorm:"foreignKey:ParentID"`
}

type QueryRelationCollisionChild struct {
	ID       uint
	ParentID uint
}

func TestGenerateSchema_SkipsQueryWhenRelationCollides(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
	).Generate(&QueryRelationCollisionParent{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "query_relation_collision_parent_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "type queryRelationCollisionParent struct")
	assert.NotContains(t, generated, ") Query() *query.Builder[")
}

// IgnoredFieldRelationParent has both a gorm:"-" field (covers eachMember's
// DBName==\"\" branch) and an association (covers eachMember's relation loop).
type IgnoredFieldRelationParent struct {
	ID       uint
	Ignored  string                      `gorm:"-"`
	Children []IgnoredFieldRelationChild `gorm:"foreignKey:ParentID"`
}

type IgnoredFieldRelationChild struct {
	ID       uint
	ParentID uint
}

func TestGenerateSchema_HandlesIgnoredFieldsAndRelations(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
	).Generate(&IgnoredFieldRelationParent{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "ignored_field_relation_parent_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.NotContains(t, generated, "Ignored ")
	assert.Contains(t, generated, "Children query.Association[")
}

func TestGenerateSchema_DryRunReadError(t *testing.T) {
	// Make the target file path point at a directory so os.ReadFile fails with
	// a non-IsNotExist error, exercising the read-error branch in verifyDryRun.
	outDir := t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(outDir, "user_gen.go"), 0755))

	err := New(
		WithOutputDir(outDir),
		WithPackageName("schemagen"),
		WithDryRun(true),
	).Generate(&User{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "read existing file")
}
