package schemagen

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/im-wmkong/gorm-query/example/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

type user struct {
	gorm.Model
	UserName string `gorm:"column:user_name;size:255;not null"`
	Email    string `gorm:"column:email;size:255;unique"`
	Age      int    `gorm:"column:age"`
	Status   int    `gorm:"column:status;default:1"` // 1: active, 0: inactive
}

type localSchemaModel struct {
	ID uint
}

type emptySchemaModel struct{}

type partiallyIgnoredSchemaModel struct {
	ID      uint
	Name    string `gorm:"column:name"`
	Ignored string `gorm:"-"`
}

type testLogger struct {
	infoCalls  int
	debugCalls int
	warnCalls  int
}

func (l *testLogger) Debug(string, ...any) { l.debugCalls++ }
func (l *testLogger) Info(string, ...any)  { l.infoCalls++ }
func (l *testLogger) Warn(string, ...any)  { l.warnCalls++ }

func TestFilterNilModels(t *testing.T) {
	filtered, nilCount := New().filterNilModels([]any{nil, &user{}, nil, &localSchemaModel{}})
	require.Len(t, filtered, 2)
	assert.Equal(t, 2, nilCount)
	assert.IsType(t, &user{}, filtered[0])
	assert.IsType(t, &localSchemaModel{}, filtered[1])
}

func TestGeneratorResolvePackageName(t *testing.T) {
	t.Run("explicit package name wins", func(t *testing.T) {
		g := New(WithPackageName("model"))
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "model", pkgName)
	})

	t.Run("inferred from default output dir", func(t *testing.T) {
		g := New()
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "schema", pkgName)
	})

	t.Run("inferred from custom output dir", func(t *testing.T) {
		g := New(WithOutputDir("./path/to/mypkg"))
		pkgName, err := g.packageName()
		require.NoError(t, err)
		assert.Equal(t, "mypkg", pkgName)
	})

	t.Run("fails when output dir is not a valid identifier", func(t *testing.T) {
		g := New(WithOutputDir("./invalid-dir"))
		_, err := g.packageName()
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unable to resolve package name")
	})
}

func TestGeneratorCheckSameModelPackage(t *testing.T) {
	g := New()

	t.Run("single model passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage([]any{&user{}}))
	})

	t.Run("empty slice passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage(nil))
	})

	t.Run("same package passes", func(t *testing.T) {
		require.NoError(t, g.checkSamePackage([]any{&user{}, &localSchemaModel{}}))
	})

	t.Run("anonymous struct fails with no package path", func(t *testing.T) {
		err := g.checkSamePackage([]any{&user{}, &struct{ ID uint }{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("first model has no package path", func(t *testing.T) {
		err := g.checkSamePackage([]any{&struct{ ID uint }{}, &user{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("different real packages fail", func(t *testing.T) {
		// schemagen.user and example/model.User live in different real packages.
		err := g.checkSamePackage([]any{&user{}, &model.User{}})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "all models must be in the same package")
	})
}

func TestGenerateSchema_SuccessAndIdempotent(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "ignored_test.go"), []byte("package ignored\n"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "notes.txt"), []byte("plain text"), 0644))
	require.NoError(t, os.WriteFile(filepath.Join(outDir, "invalid.go"), []byte("var broken = 1\n"), 0644))
	require.NoError(t, os.Mkdir(filepath.Join(outDir, "nested"), 0755))
	require.NoError(t, os.Symlink(filepath.Join(outDir, "missing.go"), filepath.Join(outDir, "broken_link.go")))

	tl := &testLogger{}
	g := New(
		WithOutputDir(outDir),
		WithPackageName("model"),
		WithNamingStrategy(schema.NamingStrategy{SingularTable: true}),
		WithLogger(tl),
	)

	err := g.Generate(&user{}, &user{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, generated, "package model")
	assert.Contains(t, generated, "var user = struct")
	assert.Contains(t, generated, "UserName")
	assert.Contains(t, generated, "query.Column")
	assert.Contains(t, generated, "DeletedAt query.Column")
	assert.Contains(t, generated, `UserName:  "user_name"`)
	assert.Contains(t, generated, `import query "github.com/im-wmkong/gorm-query/query"`)

	// First run: Info contains "generating schema..." and "generated ...".
	assert.Equal(t, 2, tl.infoCalls)
	// Duplicate user triggers one Warn.
	assert.Equal(t, 1, tl.warnCalls)
	assert.Greater(t, tl.debugCalls, 0)

	prevInfo := tl.infoCalls
	err = g.Generate(&user{})
	require.NoError(t, err)
	// Idempotent: unchanged content skips writing; only Debug is emitted.
	// Info should not increase except "generating schema...".
	assert.Equal(t, prevInfo+1, tl.infoCalls)
}

func TestGenerateSchema_DefaultLayoutMatchesSchemaPackage(t *testing.T) {
	workDir := t.TempDir()

	originalWD, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(workDir))
	t.Cleanup(func() {
		require.NoError(t, os.Chdir(originalWD))
	})

	err = New().Generate(&user{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(workDir, "schema", "user_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "package schema")
	assert.Contains(t, generated, "var user = struct")
	assert.Contains(t, generated, "UserName  query.Column")
	assert.Contains(t, generated, `UserName:  "user_name"`)
}

func TestGenerateSchema_WithExplicitPackageNameForMixedModels(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("model"),
	).Generate(&user{}, &localSchemaModel{})
	require.NoError(t, err)

	userContent, err := os.ReadFile(filepath.Join(outDir, "user_gen.go"))
	require.NoError(t, err)
	localContent, err := os.ReadFile(filepath.Join(outDir, "local_schema_model_gen.go"))
	require.NoError(t, err)

	assert.Contains(t, string(userContent), "user provides query columns and associations for the user model.")
	assert.Contains(t, string(userContent), "var user = struct")
	assert.Contains(t, string(localContent), "localSchemaModel provides query columns and associations for the localSchemaModel model.")
	assert.Contains(t, string(localContent), "var localSchemaModel = struct")
	assert.Contains(t, string(localContent), `ID: "id"`)
}

func TestGenerateSchema_SkipsModelsWithoutSchemaFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
	).Generate(&emptySchemaModel{})
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "empty_schema_model_gen.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
}

func TestGenerateSchema_SkipsIgnoredFields(t *testing.T) {
	outDir := t.TempDir()

	err := New(
		WithOutputDir(outDir),
		WithPackageName("test"),
	).Generate(&partiallyIgnoredSchemaModel{})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(outDir, "partially_ignored_schema_model_gen.go"))
	require.NoError(t, err)

	generated := string(content)
	assert.Contains(t, generated, "partiallyIgnoredSchemaModel provides query columns and associations for the partiallyIgnoredSchemaModel model.")
	assert.Contains(t, generated, "ID:")
	assert.Contains(t, generated, "Name query.Column")
	assert.NotContains(t, generated, "Ignored query.Column")
	assert.NotContains(t, generated, `Ignored: "`)
}

func TestGenerateSchema_DryRun(t *testing.T) {
	outDir := t.TempDir()

	g := New(WithOutputDir(outDir), WithPackageName("model"))
	require.NoError(t, g.Generate(&user{}))

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("model"),
		WithDryRun(true),
	)
	require.NoError(t, dryRunGenerator.Generate(&user{}))

	generatedFile := filepath.Join(outDir, "user_gen.go")
	// Overwrite the generated file with different content so dry-run detects it's outdated.
	require.NoError(t, os.WriteFile(generatedFile, []byte("package model\n"), 0644))

	err := dryRunGenerator.Generate(&user{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file outdated")
	assert.Contains(t, err.Error(), generatedFile)
}

func TestGenerateSchema_DryRunMissingFile(t *testing.T) {
	outDir := t.TempDir()

	dryRunGenerator := New(
		WithOutputDir(outDir),
		WithPackageName("model"),
		WithDryRun(true),
	)

	err := dryRunGenerator.Generate(&user{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated file missing")
	assert.Contains(t, err.Error(), filepath.Join(outDir, "user_gen.go"))
}

func TestGenerateSchema_ErrorScenarios(t *testing.T) {
	t.Run("no models", func(t *testing.T) {
		err := New().Generate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no models provided")
	})

	t.Run("WithLogger nil does not panic", func(t *testing.T) {
		g := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("model"),
			WithLogger(nil),
		)
		err := g.Generate(&user{})
		require.NoError(t, err)
	})

	t.Run("mixed packages without explicit package name", func(t *testing.T) {
		// Use an anonymous struct as the second arg (reflect.Type.PkgPath() == "") to trigger
		// the "no package path" validation without depending on example/model.
		err := New(WithOutputDir(t.TempDir())).Generate(&user{}, &struct{ ID uint }{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "no package path")
	})

	t.Run("package mismatch in output dir", func(t *testing.T) {
		outDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(outDir, "existing.go"), []byte("// generated elsewhere\n\npackage otherpkg\n"), 0644))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "package mismatch")
	})

	t.Run("create output dir failed", func(t *testing.T) {
		baseDir := t.TempDir()
		blockedPath := filepath.Join(baseDir, "blocked")
		require.NoError(t, os.WriteFile(blockedPath, []byte("not a directory"), 0644))

		err := New(WithOutputDir(blockedPath)).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "create output dir failed")
	})

	t.Run("detect package failed", func(t *testing.T) {
		outDir := filepath.Join(t.TempDir(), "locked")
		require.NoError(t, os.Mkdir(outDir, 0000))
		t.Cleanup(func() {
			require.NoError(t, os.Chmod(outDir, 0755))
		})

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "detect package failed")
	})

	t.Run("schema parse failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("broken"),
		).Generate(123)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "gorm schema parse failed")
	})

	t.Run("render failed", func(t *testing.T) {
		err := New(
			WithOutputDir(t.TempDir()),
			WithPackageName("invalid-package"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "render failed")
	})

	t.Run("package name resolution failed", func(t *testing.T) {
		// outputDir ends with an invalid Go identifier and no explicit package name,
		// so packageName() returns an error.
		outDir := filepath.Join(t.TempDir(), "invalid-dir")
		require.NoError(t, os.MkdirAll(outDir, 0755))

		err := New(WithOutputDir(outDir)).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "unable to resolve package name")
	})

	t.Run("target path is a directory", func(t *testing.T) {
		outDir := t.TempDir()
		// Create a directory at the target file path so both os.ReadFile and os.WriteFile fail.
		require.NoError(t, os.Mkdir(filepath.Join(outDir, "user_gen.go"), 0755))

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "read existing file")
		assert.Contains(t, err.Error(), "failed")
	})

	t.Run("write file failed on read-only dir", func(t *testing.T) {
		baseDir := t.TempDir()
		outDir := filepath.Join(baseDir, "readonly")
		require.NoError(t, os.Mkdir(outDir, 0755))
		// Make the directory read-only so os.ReadFile returns ErrNotExist (treated as "exists=false"),
		// while os.WriteFile fails with a permission error.
		require.NoError(t, os.Chmod(outDir, 0555))
		t.Cleanup(func() {
			_ = os.Chmod(outDir, 0755)
		})

		err := New(
			WithOutputDir(outDir),
			WithPackageName("model"),
		).Generate(&user{})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "write file")
		assert.Contains(t, err.Error(), "failed")
	})
}

func TestNopLogger_DoesNotPanic(t *testing.T) {
	l := NopLogger()
	require.NotNil(t, l)

	// no output asserted, just ensure these methods are executed
	l.Debug("debug %s", "x")
	l.Info("info %d", 1)
	l.Warn("warn %v", nil)
}
