// Code generated by colgen. DO NOT EDIT.

package columns

import query "github.com/im-wmkong/gorm-query/query"

// User provides query columns for the User model.
var User = struct {
	ID        query.Column
	CreatedAt query.Column
	UpdatedAt query.Column
	DeletedAt query.Column
	UserName  query.Column
	Email     query.Column
	Age       query.Column
	Status    query.Column
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	UserName:  "user_name",
	Email:     "email",
	Age:       "age",
	Status:    "status",
}
