name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Generate Code
      # 在跑测试前，先确保生成器能正常工作
      run: |
        go generate ./example/...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.62.2
        args: --timeout=5m

    - name: Test (with coverage)
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.out
        if-no-files-found: error
