name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.18' # 建议与你 go.mod 中的版本保持一致

    - name: Install dependencies
      run: go mod download

    - name: Generate Code
      # 在跑测试前，先确保生成器能正常工作
      run: |
        go install ./cmd/gen-props
        go generate ./example/...

    - name: Test
      run: go test -v -race ./...
